#!/usr/bin/env bash

# Delete PR app and merge PR

PR_NUM=$(hub pr show -f '%I')

if [ -z "$PR_NUM" ]
then
  read -r -p "GitHub PR number?? " pr_number
else
  pr_number=$PR_NUM
fi

gh pr checks "$pr_number"
gh pr view "$pr_number"

while true; do
  read -p -r "Do you want to continue? " yn
  case $yn in
    [Yy]* ) gh pr merge "$pr_number" --merge --admin;heroku apps:destroy -a indigo-shop-pr-"$pr_number" --confirm indigo-shop-pr-"$pr_number"; break;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
  esac
done
